/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Logic.Passenger;
import Views.Buttons.SeatFactory;
import java.awt.Component;
import java.awt.List;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author lmfg0
 */
public class MainPlane extends javax.swing.JFrame {
    
    private int amountEconomy;
    private int amountExecutive;
//    private final List<SeatFactory> listSeat = new ArrayList<>();
    
    public MainPlane(int amountEconomy, int amountExecutive) {
        this.amountEconomy = amountEconomy;
        this.amountExecutive = amountExecutive;
        initComponents();
        initUI();
    }

    /**
     * Creates new form MainPlane
     */
    public MainPlane() {
        initComponents();
        initUI();
    }
    
    private void initUI(){
        this.setLocationRelativeTo(null);
        
        // Uso del método para agregar asientos ejecutivos
        addSeats("executive", 242, 152, 57, 26, amountExecutive, 4, 67, 100);

        // Uso del método para agregar asientos económicos
        addSeats("economy", 175, 152 + (amountExecutive / 4) * (26 + 10), 57, 26, amountEconomy, 6, 67, 100);
        
        pack();

    }
    
    private void addSeats(String type, int initialX, int initialY, int seatWidth, int seatHeight, int amount, int maxColumns, int incrementSmall, int incrementLarge) {
        int currentX = initialX;
        int currentY = initialY;
        int column = 1;
    
        for (int i = 0; i < amount; i++) {
            SeatFactory seat = new SeatFactory(type, currentX, currentY, seatWidth, seatHeight, String.valueOf(i + 1));
            getContentPane().add(seat.createButton());
//            listSeat.Add(seat);
            
            // Ajuste de posición en X y control de columnas
            if (column < maxColumns) {
                currentX += (column % (maxColumns / 2) == 0) ? incrementLarge : incrementSmall;
                column++;
            } else {
            // Nueva fila
                column = 1;
                currentY += seatHeight + 10; // Ajuste para la siguiente fila, agregando espacio entre filas
                currentX = initialX;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonRegister = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonRegister.setText("REGISTER PASSENGER");
        buttonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegisterActionPerformed(evt);
            }
        });

        jLabel1.setText("PILOT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(285, Short.MAX_VALUE)
                .addComponent(buttonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(253, 253, 253))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(buttonRegister)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(564, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegisterActionPerformed
        RegisterPassenger register = new RegisterPassenger();
        register.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        System.out.print("funciona");
        register.addWindowListener(new WindowAdapter(){
                @Override
                public void windowClosed(WindowEvent e){                
                    if (register.IsCorrect()){
                        onWindowClose(e, register.getInfoPassenger());
                    }                                     
                }
            }     
        );
        register.setVisible(true);
    }//GEN-LAST:event_buttonRegisterActionPerformed

    private void onWindowClose(WindowEvent e, Passenger passenger){
        JButton button = findButtonById("economy_1");
        button.setText("Reservado");
        button.revalidate();
        button.repaint();
    }
    
    public JButton findButtonById(String id) {
        for (Component comp : getContentPane().getComponents()) {
            if (comp instanceof JButton) {
                JButton button = (JButton) comp;
                if (id.equals(button.getName())) {
                    return button;
            }
        }
    }
    System.out.println("Botón con ID " + id + " no encontrado.");
    return null;  // Retorna null si no encuentra el botón
}

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPlane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPlane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPlane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPlane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPlane().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonRegister;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
