/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Logic.ClassType;
import Logic.Passenger;
import Logic.SeatType;

/**
 *
 * @author lmfg0
 */
public class RegisterPassenger extends javax.swing.JFrame {
    
    private Passenger _passenger;
    private boolean isCorrect;
  
    /**
     * Creates new form RegisterPassenger
     */
    public RegisterPassenger() {
        initComponents();
        addButtonGroup();
        this._passenger = new Passenger();
        this.isCorrect = false;
        showInformation();
    }
    
    public boolean IsCorrect() {
        return isCorrect;
    }
    
    public void setInfoPassenger(Passenger passenger){
        this._passenger = passenger;
        showInformation();
    }
    
    public Passenger getInfoPassenger(){
        return this._passenger;
    }
    
    private void showInformation(){
        txtFullName.setText(_passenger.getName());
        txtId.setText(_passenger.getId());
        
        if (_passenger.getClassType() == ClassType.Economy){
            buttonEconomy.setSelected(true);
        } else {
            buttonExecutive.setSelected(true);
        }
        
        switch (_passenger.getSeatType()) {
            case Window:
                buttonWindowSeat.setSelected(true);
                break;
            case Aisle:
                buttonAisleSeat.setEnabled(true);
                break;
            default:
                buttonMiddleSeat.setEnabled(true);
                break;
        }
    }
    
    private void addButtonGroup(){
        buttonGroupClassType.add(buttonEconomy);
        buttonGroupClassType.add(buttonExecutive);
        
        buttonGroupSeatPreference.add(buttonAisleSeat);
        buttonGroupSeatPreference.add(buttonMiddleSeat);
        buttonGroupSeatPreference.add(buttonWindowSeat);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupClassType = new javax.swing.ButtonGroup();
        buttonGroupSeatPreference = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buttonEconomy = new javax.swing.JRadioButton();
        buttonExecutive = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        buttonWindowSeat = new javax.swing.JRadioButton();
        buttonAisleSeat = new javax.swing.JRadioButton();
        buttonMiddleSeat = new javax.swing.JRadioButton();
        buttonAceept = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("BASIC INFORMATION");

        jLabel2.setText("FULL NAME");

        txtFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFullNameActionPerformed(evt);
            }
        });

        jLabel3.setText("ID");

        jLabel4.setText("PREFERENCES");

        jLabel5.setText("CLASS TYPE");

        buttonEconomy.setText("ECONOMY");
        buttonEconomy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEconomyActionPerformed(evt);
            }
        });

        buttonExecutive.setText("EXECUTIVE");
        buttonExecutive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExecutiveActionPerformed(evt);
            }
        });

        jLabel6.setText("SEAT PREFERENCE");

        buttonWindowSeat.setText("WINDOW SEAT");
        buttonWindowSeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWindowSeatActionPerformed(evt);
            }
        });

        buttonAisleSeat.setText("AISLE SEAT");
        buttonAisleSeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAisleSeatActionPerformed(evt);
            }
        });

        buttonMiddleSeat.setText("MIDDLE SEAT");
        buttonMiddleSeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMiddleSeatActionPerformed(evt);
            }
        });

        buttonAceept.setText("ACCEPT");
        buttonAceept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAceeptActionPerformed(evt);
            }
        });

        buttonCancel.setText("CANCEL");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFullName)
                            .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)))
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonWindowSeat)
                            .addComponent(buttonEconomy))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonExecutive)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonMiddleSeat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addComponent(buttonAisleSeat)))))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(buttonAceept)
                        .addGap(45, 45, 45)
                        .addComponent(buttonCancel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEconomy)
                    .addComponent(buttonExecutive))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonWindowSeat)
                    .addComponent(buttonMiddleSeat)
                    .addComponent(buttonAisleSeat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAceept)
                    .addComponent(buttonCancel))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFullNameActionPerformed

    private void buttonExecutiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExecutiveActionPerformed
        buttonMiddleSeat.setSelected(false);
        buttonMiddleSeat.setEnabled(false);
        _passenger.setClassType(ClassType.Executive);
    }//GEN-LAST:event_buttonExecutiveActionPerformed

    private void buttonEconomyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEconomyActionPerformed
        buttonMiddleSeat.setEnabled(true);
        _passenger.setClassType(ClassType.Economy);
        
    }//GEN-LAST:event_buttonEconomyActionPerformed

    private void buttonAceeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAceeptActionPerformed
        _passenger.setName(txtFullName.getText());
        _passenger.setId(txtId.getText());
        isCorrect = true;
        dispose();
    }//GEN-LAST:event_buttonAceeptActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonWindowSeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWindowSeatActionPerformed
        _passenger.setSeatType(SeatType.Window);        
    }//GEN-LAST:event_buttonWindowSeatActionPerformed

    private void buttonMiddleSeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMiddleSeatActionPerformed
        _passenger.setSeatType(SeatType.Middle);
    }//GEN-LAST:event_buttonMiddleSeatActionPerformed

    private void buttonAisleSeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAisleSeatActionPerformed
        _passenger.setSeatType(SeatType.Aisle);
    }//GEN-LAST:event_buttonAisleSeatActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPassenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPassenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPassenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPassenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPassenger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAceept;
    private javax.swing.JRadioButton buttonAisleSeat;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JRadioButton buttonEconomy;
    private javax.swing.JRadioButton buttonExecutive;
    private javax.swing.ButtonGroup buttonGroupClassType;
    private javax.swing.ButtonGroup buttonGroupSeatPreference;
    private javax.swing.JRadioButton buttonMiddleSeat;
    private javax.swing.JRadioButton buttonWindowSeat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
